services:
  api:
    build:
      context: .          # путь к проекту
      dockerfile: Dockerfile
    image: rom3ik/al_narcis_api:latest
    container_name: api
    ports:
      - "5310:5310"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    restart: always
